### ISSUE TITLE
VPS上出现的提示，怎么解决？

### ISSUE THREAD

**Issue by 0oVicero0** [yxjxx/v2ex_daily_mission#5]
/usr/local/lib/python2.7/dist-packages/bs4/**init**.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))

**Comment by yxjxx** [comment]
@0oVicero0 

http://stackoverflow.com/questions/33511544/how-to-get-rid-of-beautifulsoup-user-warning

https://github.com/ckreibich/scholar.py/issues/49

try this
`self.soup = BeautifulSoup(html)`
to
`self.soup = BeautifulSoup(html, 'html.parser')`
